"""add thread_id column

Revision ID: 3974292c8979
Revises: 2bf255086a3b
Create Date: 2023-12-13 17:26:14.857163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3974292c8979'
down_revision: Union[str, None] = '2bf255086a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('thread_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'thread_id')
    # ### end Alembic commands ###
